version: "3.8"

services:
  aruba_exporter:
    build: ./
    volumes:
      - ./:/usr/src/app/
    ports:
      - "9909:9909"
    entrypoint:
      - /go/bin/CompileDaemon
      - -directory=./
      - -build=go build -o ./build/aruba_exporter       
      - -command=./build/aruba_exporter -config.file ./config.yaml
